# try except and finally block

x = 12
try:
    print(x)
except:
    print("Something went wrong in program..")
finally:
    print("You are in the finally block...")